spring.application.name=e-commerce
spring.data.mongodb.uri=mongodb://localhost:27017/mongodb
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
security.jwt.secret=R2dJd1NvcVNqQ3RzV1ZVT0hqRk1iR2RmZ1ZpZkYyMGY=  


